module.exports = {
    S3_FILE_CONTENT_MD5_TAG: "MD5",
    S3_FILE_CONTENT_SCAN_START_TAG: "SCAN_START",
    S3_FILE_CONTENT_SCAN_END_TAG: "SCAN_END",
    S3_FILE_CONTENT_SCAN_IS_INFECTED_TAG: "SCAN_IS_INFECTED"
};
