extends:
  - eslint:recommended
rules:
  no-useless-escape: 1
  eqeqeq: 2
  semi: 2
  quotes:
    - 2
    - double
  import/named: 2
  import/export: 2
  import/no-mutable-exports: 2
  import/first: 2
  import/no-duplicates: 2
  import/no-unresolved: 2
  import/default: 2
  no-global-assign: 2
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    modules: true
env:
  node: true
  es6: true
  mocha: true
globals:
  Promise: true
plugins:
  - import
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .json
