language: node_js
dist: trusty
node_js:
  - '8'
  - '11'
  - '10'
env:
  global:
    - SLAMSCAN_FRESHCLAM_BINARY_PATH=./build/bin/freshclam
    - SLAMSCAN_FRESHCLAM_CONFIG_PATH=./build/etc/freshclam.conf
    - SLAMSCAN_CLAMSCAN_BINARY_PATH=./build/bin/clamscan
    - SLAMSCAN_CLAMSCAN_DB_PATH=./build/defs
    - secure: kg4LyuEV/LbATfTiLdGRb5dkFt8EXZshILwDQdyeqgnqtMmT9iFgUTvt5mXWaivJ9kDkxS7Iz7kpFXvRZUiicFc4NdDH2XljMQmzMfcLH1fGs/jwI42CiKxv8wW2ZKpAr6cITkexHZndna1GkluEqQeONymT0dtLEzURWJDqF4+iYmzXH6LdbSVq5onAxDHxiS8S9/JLd1Lwd59tJPPLBIW9BtQMypNlknhEpHXeOmbPNWOoHDcSUXSHQoho3gbl4bOvuh5cg9m8PPFRNRXX7F5GdcUuqfrNx2I0H0h0L62gnK9r+5kbM0zVIAdMG9FkISAF5UIKAnC6nsdwNQbFQFvqzGx2BWhFsIo98dALmHN0NQHNZh4JzN4W6FA6b3Wdcsz7QSGjeL1rs9nf80ANPRWUrLiauczrNmeUB5c7Qzi9x432H1tIxf5YAxgv/ExB2H1To4bzyYoBBJJtFJ0DI9vtI2Y85ME1rXKKdK+hZJJcLDlpqsZZ3bg2soZemGXrGTzKMzy8UtM/3fB/V+WfEyv7vXMa5PIsgd0gfi9VmC7sHeC2v1N1ISc4dkZL/d+LnUmp1EDsFbKodYI19CqpI4zjvQ9iIkUS8ksKDz8g9GyopKRB7Z1q0H8CFfzfv3sptcNEPSK6yCZA6oG59puuQYklpV7tRX4iPZsJ+JE8M1E=
cache:
  timeout: 1200
  directories:
    - "$HOME/.npm"
before_install:
  - uname -a
  - lscpu
  - npm install -g npm
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/build/lib
  - sudo ln -s /lib/x86_64-linux-gnu/libssl.so.1.0.0 /lib/x86_64-linux-gnu/libssl.so.10
  - sudo ln -s /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /lib/x86_64-linux-gnu/libcrypto.so.10
before_script:
  - npm run pretest
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run cover:actual
after_script:
  - npm run cover:collect
  - npm run coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
before_deploy:
  - git config --local user.name "$TRAVIS_AUTHOR_NAME"
  - git config --local user.email "$TRAVIS_AUTHOR_EMAIL"
deploy:
  provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    branch: master
    node: 8
addons:
  apt:
    packages:
      - libssl-dev
      - libssl1.0.0
