db-files:
  - test://test.test/test/test.1
  - test://test.test/test/test.2
  - test://test.test/test/test.3
  - test://test.test/test/test.4
  - test://test.test/test/test.5

clamscan:
  testing_mode: true
